export const products = [
  {
    id: 1,
    name: 'Modern Sofa',
    price: 899.99,
    category: 'Living Room',
    image: '/images/products/grey sofa.png',
    description: 'Comfortable modern sofa with premium fabric',
    features: [
      'Premium fabric upholstery',
      'Deep seating for maximum comfort',
      'Modern design with clean lines',
      'Durable wood frame',
      'Easy to clean and maintain',
    ],
    dimensions: {
      width: '84 inches',
      depth: '36 inches',
      height: '32 inches',
    },
    rating: 4.5,
    reviews: 128,
  },
  {
    id: 2,
    name: 'Dining Table',
    price: 599.99,
    category: 'Dining Room',
    image: '/images/products/round table.png',
    description: 'Elegant dining table for 6 people',
    features: [
      'Solid wood construction',
      'Seats up to 6 people',
      'Modern minimalist design',
      'Easy to assemble',
      'Scratch-resistant surface',
    ],
    dimensions: {
      width: '72 inches',
      depth: '36 inches',
      height: '30 inches',
    },
    rating: 4.2,
    reviews: 95,
  },
  {
    id: 3,
    name: 'Coffee Table',
    price: 299.99,
    category: 'Living Room',
    image: '/images/products/table drawer.png',
    description: 'Modern coffee table with glass top',
    features: [
      'Tempered glass top',
      'Solid wood legs',
      'Modern design',
      'Easy to clean',
    ],
    dimensions: {
      width: '48 inches',
      depth: '24 inches',
      height: '18 inches',
    },
    rating: 4.0,
    reviews: 80,
  },
  {
    id: 4,
    name: 'Bed Frame',
    price: 799.99,
    category: 'Bedroom',
    image: '/images/products/bed.png',
    description: 'King size bed frame with storage',
    features: [
      'King size',
      'Built-in storage',
      'Solid wood construction',
      'Easy to assemble',
    ],
    dimensions: {
      width: '80 inches',
      depth: '76 inches',
      height: '14 inches',
    },
    rating: 4.3,
    reviews: 110,
  },
  {
    id: 5,
    name: 'Desk',
    price: 399.99,
    category: 'Office',
    image: '/images/products/dresser.png',
    description: 'Modern office desk with cable management',
    features: [
      'Cable management',
      'Spacious surface',
      'Modern design',
      'Easy to assemble',
    ],
    dimensions: {
      width: '60 inches',
      depth: '30 inches',
      height: '30 inches',
    },
    rating: 4.1,
    reviews: 60,
  },
  {
    id: 6,
    name: 'Bookshelf',
    price: 249.99,
    category: 'Living Room',
    image: '/images/products/bookshelf.png',
    description: 'Tall bookshelf with multiple shelves',
    features: [
      'Multiple shelves',
      'Tall design',
      'Sturdy construction',
      'Easy to assemble',
    ],
    dimensions: {
      width: '36 inches',
      depth: '12 inches',
      height: '72 inches',
    },
    rating: 4.0,
    reviews: 45,
  },
]; 